trigger:
  branches:
    include:
      - main  # Kör pipeline när kod pushas till main

pool:
  vmImage: 'ubuntu-latest'  # Bygg på en Linux-miljö

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'  # Ändra om du använder .NET 6 eller 7

  - script: dotnet restore
    displayName: 'Restore NuGet packages'

  - script: dotnet build --configuration Release
    displayName: 'Build the project'

  - script: dotnet test --configuration Release
    displayName: 'Run unit tests (if any)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'bin/Release'
      artifactName: 'drop'
