trigger:
  branches:
    include:
      - main 

pool:
  name: Default 

steps:
  - script: echo "Agent is running!"
    displayName: 'Test Self-Hosted Agent'

  - task: DotNetCoreCLI@2
    displayName: 'Build and Run'
    inputs:
      command: 'build'
      projects: 'MotionConnect/MotionConnect.csproj'
